# Generated by Django 4.0.4 on 2022-08-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_events_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_city',
            field=models.CharField(default='', max_length=50),
        ),
    ]
