# Generated by Django 4.0.4 on 2022-08-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_event_date_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='', upload_to='events/event_images'),
        ),
    ]
