# Generated by Django 4.0.4 on 2022-08-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_state',
        ),
        migrations.AddField(
            model_name='event',
            name='event_details',
            field=models.TextField(default='NA'),
        ),
    ]
