# Generated by Django 4.0.4 on 2022-08-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_event_state_event_event_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/event_images'),
        ),
    ]
